/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fcb35af3-16fe-4567-beaa-57a650d129ba",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Dwq5R7VyZ",
    "aws_user_pools_web_client_id": "5l58s6jtuvcj8cgrhqe1ft7ldo",
    "oauth": {}
};


export default awsmobile;
