asepyFishSwarm:
  # component: "@sls-next/serverless-component@1.19.0"
  component: "@sls-next/serverless-component@3.5.3-alpha.4"
  inputs:
    memory:
      defaultLambda: 2048
      apiLambda: 2048
    timeout:
      defaultLambda: 30
    env:
      NEXT_PUBLIC_API_BASE: ${env.NEXT_PUBLIC_API_BASE}
      NEXT_PUBLIC_API_KEY: ${env.NEXT_PUBLIC_API_KEY}
      NEXT_PUBLIC_SITE_URL: ${env.NEXT_PUBLIC_SITE_URL}
