name: CD Prod

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing NPM dependencies
        run: npm install
      - name: Building
        run: npm run build
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.API_BASE }}
          NEXT_PUBLIC_API_KEY: ${{ secrets.API_KEY }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.PUBLIC_SITE_URL }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: sa-east-1
      - run: aws s3 sync ./out s3://fischwarm-frontend --acl public-read
